language: objective-c
osx_image: xcode7
before_install:
- gem install cocoapods
script:
- xcodebuild -workspace StoryboardKit.xcworkspace -scheme StoryboardKit -sdk macosx build test GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=YES GCC_GENERATE_TEST_COVERAGE_FILES=YES
after_success:
- bash <(curl -s https://codecov.io/bash)
